"""Rebuild MambaIR Set5 per-k summaries from per-run surgery and distill metadata.

Each variant reads ``ts_surgery_mambair_x{s}_topk{k}_fast{suffix}.json`` (pre-distill PSNR/SSIM) and
``ts_distill_mambair_x{s}_topk{k}{dsuffix}.json`` (post-distill PSNR). Post-distill SSIM is not
logged by the distill stage, so it is omitted. Writes ``artifacts/metadata/mambair_x{s}{tag}_set5_by_k.json``.
"""

from __future__ import annotations

import json
import os
from typing import Dict, List, Optional

META = "artifacts/metadata"
KS = [0, 1, 2, 4, 16, 64, 256]

# tag, scale, surgery suffix, distill suffix, variant label
VARIANTS = [
    ("", 2, "", "", "calibrated_tail_mass"),
    ("", 4, "", "", "calibrated_tail_mass"),
    ("_exact", 4, "_tailmass_exact", "_tailmass_exact", "exact_tail_mass"),
    ("_tailmass0", 4, "_tailmass0", "_tailmass0", "tail_drop_q0"),
]


def _load(path: str) -> Optional[Dict]:
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)


def summarize(tag: str, scale: int, ssuf: str, dsuf: str, variant: str) -> Optional[str]:
    rows: List[Dict] = []
    for k in KS:
        surg = _load(f"{META}/ts_surgery_mambair_x{scale}_topk{k}_fast{ssuf}.json")
        if surg is None:
            continue
        cal = surg["calibration"]
        dist = _load(f"{META}/ts_distill_mambair_x{scale}_topk{k}{dsuf}.json")
        post = dist["calibration"]["student_post_distill_val_acc"] if dist else None
        rows.append(
            {
                "k": k,
                "ref_psnr": cal["ref_val_acc"],
                "ref_ssim": cal.get("ref_val_ssim"),
                "pre_psnr": cal["student_pre_ft_val_acc"],
                "pre_ssim": cal.get("student_pre_ft_val_ssim"),
                "post_psnr": post,
                "calibrated_q_mean": cal.get("gibbs_tail_prob_eps_calibrated_mean"),
                "surgery_metadata": f"ts_surgery_mambair_x{scale}_topk{k}_fast{ssuf}.json",
                "distill_metadata": f"ts_distill_mambair_x{scale}_topk{k}{dsuf}.json" if dist else None,
            }
        )
    if not rows:
        return None
    out = f"{META}/mambair_x{scale}{tag}_set5_by_k.json"
    summary = {
        "dataset": "Set5",
        "train": "DIV2K",
        "scale": scale,
        "variant": variant,
        "note": "generated by scripts/summarize_mambair.py from per-run metadata; "
        "pre = surgery before distill, post = after distill (PSNR only)",
        "rows": rows,
    }
    with open(out, "w") as f:
        json.dump(summary, f, indent=1)
    return out


def main() -> None:
    for spec in VARIANTS:
        out = summarize(*spec)
        if out:
            print(f"wrote {out}")


if __name__ == "__main__":
    main()
